### PR TITLE
Master

### PR DESCRIPTION
**Pull request by hsboykjh**
backend engineer test
( Jihoon Kwon )

### CODE REVIEW

**Comment by bzz** [comment]
Hi @hsboykjh thank you for submitting the challenge! You did a great job decoupling the code, adding tests, etc.

Not sure what is the current status - if it is finished or not, and if it is - how to run it, so please feel free to point me to build\run instructions for this project in case I have missed them.

I have tried standard for java projects `mvn package` and had some warning and errors:

```
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.jihoon:zeplTest:jar:1.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 123, column 21
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building zeplTest 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------

.............................

[ERROR] symbol:   method when(com.jihoon.model.Task)
[ERROR] location: class com.jihoon.service.TodoServiceImplTest
[ERROR] /Users/alex/Documents/_NFLabs/data-engineering-challenge/src/test/java/com/jihoon/service/TodoServiceImplTest.java:[70,9] cannot find symbol
[ERROR] symbol:   method assertEquals(int,int)
[ERROR] location: class com.jihoon.service.TodoServiceImplTest
[ERROR] /Users/alex/Documents/_NFLabs/data-engineering-challenge/src/test/java/com/jihoon/service/TodoServiceImplTest.java:[71,9] cannot find symbol
[ERROR] symbol:   method assertEquals(java.lang.Object,java.lang.String)
[ERROR] location: class com.jihoon.service.TodoServiceImplTest
[ERROR] /Users/alex/Documents/_NFLabs/data-engineering-challenge/src/test/java/com/jihoon/service/TodoServiceImplTest.java:[82,9] cannot find symbol
[ERROR] symbol:   method assertEquals(int,int)
[ERROR] location: class com.jihoon.service.TodoServiceImplTest
[ERROR] /Users/alex/Documents/_NFLabs/data-engineering-challenge/src/test/java/com/jihoon/service/TodoServiceImplTest.java:[83,9] cannot find symbol
[ERROR] symbol:   method assertEquals(java.lang.String,java.lang.String)
[ERROR] location: class com.jihoon.service.TodoServiceImplTest
[ERROR] /Users/alex/Documents/_NFLabs/data-engineering-challenge/src/test/java/com/jihoon/service/TodoServiceImplTest.java:[94,9] cannot find symbol
[ERROR] symbol:   method assertEquals(int,int)
[ERROR] location: class com.jihoon.service.TodoServiceImplTest
[ERROR] -> [Help 1]
```

**Comment by hsboykjh** [comment]
Hi @bzz,
I am sorry I missed my latest pom.xml.
Also, I check it is working on maven (mvn package)  since I usually use IntelliJ IDE as well.
If you have any problems, please let me know.

**Comment by bzz** [comment]
Thank you @hsboykjh 

But still I do not know the answer to the question from my previous message:
> Not sure what is the current status - if it is finished or not, and if it is - how to run it, so please feel free to point me to build\run instructions for this project in case I have missed them.

Would you be so kind to answer it, please?

If that helps, please imagine that one of your colleagues is willing to deploy this software, that you have developed (and submitted it to him in PullRequest with the title `master`) to the production now. How would he do that? Where are the instructions?

Please let me know if you have any questions.

**Comment by hsboykjh** [comment]
@bzz  
Firstly, I finished this challenge. 
And I added one mark down file ( todo-challenge-solution.md ) for instruction. The file has build / run instructions, configuarations and project overview etc. 

I hope it would be helpful to you to understand my solution. 

Please let me know if you have any questions.

**Pull request closed without merging**
