### PR TITLE
submission for data engineering challenge

### PR DESCRIPTION
**Pull request by jinwooe**
Maven is used as build system.

How to run the web application
# cd <project_directory>
# mvn clean package
# java -jar target/backend-challenge-0.0.1-SNAPSHOT.jar

### CODE REVIEW

**Comment by astroshim** [comment]
Hello. 
I got a following error when i want to build.
```
[INFO] 
[INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ backend-challenge ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ backend-challenge ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Copying 0 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ backend-challenge ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 13 source files to /home/nflabs/data-engineering-challenge/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:24 min
[INFO] Finished at: 2016-08-11T20:14:08+09:00
[INFO] Final Memory: 18M/121M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project backend-challenge: Fatal error compiling: invalid target release: 1.8 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```
How can i solve this?

**Comment by jinwooe** [comment]
I think you have older jdk version than jdk 1.8.
The application target version is 1.8 so you should have jdk 1.8 installed

**Comment by astroshim** [comment]
Thank you for proper answer. :+1:

**Comment by jongyoul** [comment]
@jinwooe Hi Jinwoo, for the next step, some of team members ask you about this PR one by one. This is a very important process for handling PR and we will evaluate how you handle question and review. @astroshim is the first. Good luck.

**Pull request closed without merging**
